# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modular_robot_control.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_modular_robot(object):
    def setupUi(self, MainWindow_modular_robot):
        MainWindow_modular_robot.setObjectName("MainWindow_modular_robot")
        MainWindow_modular_robot.resize(778, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_modular_robot.sizePolicy().hasHeightForWidth())
        MainWindow_modular_robot.setSizePolicy(sizePolicy)
        MainWindow_modular_robot.setMinimumSize(QtCore.QSize(778, 666))
        MainWindow_modular_robot.setMaximumSize(QtCore.QSize(778, 888))
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow_modular_robot.setFont(font)
        MainWindow_modular_robot.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow_modular_robot)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 531, 611))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(90, 70, 351, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 4, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 430, 351, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout.addWidget(self.lineEdit_12)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(80, 70, 351, 361))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_4.addWidget(self.pushButton_9, 4, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_4.addWidget(self.pushButton_16, 3, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_4.addWidget(self.pushButton_15, 0, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_4.addWidget(self.pushButton_14, 2, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_4.addWidget(self.pushButton_13, 1, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 430, 351, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_2.addWidget(self.label_45)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_2.addWidget(self.lineEdit_23)
        self.label_46 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_2.addWidget(self.label_46)
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_2.addWidget(self.pushButton_17)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 291, 551))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_24.setGeometry(QtCore.QRect(370, 430, 80, 80))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(370, 280, 80, 80))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(360, 140, 101, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(370, 100, 81, 31))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(460, 100, 59, 31))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 30, 171, 281))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_7.addWidget(self.lineEdit_28, 2, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_61.setObjectName("label_61")
        self.gridLayout_7.addWidget(self.label_61, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_62.setObjectName("label_62")
        self.gridLayout_7.addWidget(self.label_62, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_63.setObjectName("label_63")
        self.gridLayout_7.addWidget(self.label_63, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_7.addWidget(self.lineEdit_29, 3, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_70.setObjectName("label_70")
        self.gridLayout_7.addWidget(self.label_70, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_66 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_66.setObjectName("label_66")
        self.gridLayout_7.addWidget(self.label_66, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_7.addWidget(self.lineEdit_26, 0, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_69.setObjectName("label_69")
        self.gridLayout_7.addWidget(self.label_69, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_72 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_72.setObjectName("label_72")
        self.gridLayout_7.addWidget(self.label_72, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_71 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_71.setObjectName("label_71")
        self.gridLayout_7.addWidget(self.label_71, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_31.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_7.addWidget(self.lineEdit_31, 5, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_68.setObjectName("label_68")
        self.gridLayout_7.addWidget(self.label_68, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_67.setObjectName("label_67")
        self.gridLayout_7.addWidget(self.label_67, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_30.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_7.addWidget(self.lineEdit_30, 4, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_64.setObjectName("label_64")
        self.gridLayout_7.addWidget(self.label_64, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_65.setObjectName("label_65")
        self.gridLayout_7.addWidget(self.label_65, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_27.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_7.addWidget(self.lineEdit_27, 1, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(180, 30, 171, 281))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_32.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_8.addWidget(self.lineEdit_32, 2, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_73.setObjectName("label_73")
        self.gridLayout_8.addWidget(self.label_73, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_74 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_74.setObjectName("label_74")
        self.gridLayout_8.addWidget(self.label_74, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_75 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_75.setObjectName("label_75")
        self.gridLayout_8.addWidget(self.label_75, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_33.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_8.addWidget(self.lineEdit_33, 3, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_76.setObjectName("label_76")
        self.gridLayout_8.addWidget(self.label_76, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_77 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_77.setObjectName("label_77")
        self.gridLayout_8.addWidget(self.label_77, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_34.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_8.addWidget(self.lineEdit_34, 0, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_78.setObjectName("label_78")
        self.gridLayout_8.addWidget(self.label_78, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_79.setObjectName("label_79")
        self.gridLayout_8.addWidget(self.label_79, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_80 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_80.setObjectName("label_80")
        self.gridLayout_8.addWidget(self.label_80, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_35.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_8.addWidget(self.lineEdit_35, 5, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_81.setObjectName("label_81")
        self.gridLayout_8.addWidget(self.label_81, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_82 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_82.setObjectName("label_82")
        self.gridLayout_8.addWidget(self.label_82, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_8.addWidget(self.lineEdit_36, 4, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_83.setObjectName("label_83")
        self.gridLayout_8.addWidget(self.label_83, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_84 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_84.setObjectName("label_84")
        self.gridLayout_8.addWidget(self.label_84, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_37.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_8.addWidget(self.lineEdit_37, 1, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.tab_3)
        self.label_85.setGeometry(QtCore.QRect(0, 0, 141, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.tab_3)
        self.label_86.setGeometry(QtCore.QRect(180, 0, 161, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.label_99 = QtWidgets.QLabel(self.tab_3)
        self.label_99.setGeometry(QtCore.QRect(180, 310, 131, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(0, 340, 171, 221))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_126 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_126.setObjectName("label_126")
        self.gridLayout_12.addWidget(self.label_126, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_57.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_57.setReadOnly(True)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_12.addWidget(self.lineEdit_57, 3, 1, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_56.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_56.setReadOnly(True)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_12.addWidget(self.lineEdit_56, 2, 1, 1, 1)
        self.label_124 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_124.setObjectName("label_124")
        self.gridLayout_12.addWidget(self.label_124, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_125 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_125.setObjectName("label_125")
        self.gridLayout_12.addWidget(self.label_125, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_127 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_127.setObjectName("label_127")
        self.gridLayout_12.addWidget(self.label_127, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_58.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_58.setReadOnly(True)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_12.addWidget(self.lineEdit_58, 0, 1, 1, 1)
        self.label_129 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_129.setObjectName("label_129")
        self.gridLayout_12.addWidget(self.label_129, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_131 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_131.setObjectName("label_131")
        self.gridLayout_12.addWidget(self.label_131, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_132 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_132.setObjectName("label_132")
        self.gridLayout_12.addWidget(self.label_132, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_135 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_135.setObjectName("label_135")
        self.gridLayout_12.addWidget(self.label_135, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_60.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_60.setReadOnly(True)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout_12.addWidget(self.lineEdit_60, 4, 1, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_133.setObjectName("label_133")
        self.gridLayout_12.addWidget(self.label_133, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_134 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_134.setObjectName("label_134")
        self.gridLayout_12.addWidget(self.label_134, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_61.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_61.setReadOnly(True)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout_12.addWidget(self.lineEdit_61, 1, 1, 1, 1)
        self.label_148 = QtWidgets.QLabel(self.tab_3)
        self.label_148.setGeometry(QtCore.QRect(0, 310, 131, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_148.setFont(font)
        self.label_148.setObjectName("label_148")
        self.pushButton_33 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_33.setGeometry(QtCore.QRect(390, 330, 91, 61))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_34.setGeometry(QtCore.QRect(390, 470, 91, 61))
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(180, 340, 171, 221))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_62.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_62.setReadOnly(True)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_13.addWidget(self.lineEdit_62, 2, 1, 1, 1)
        self.label_137 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_137.setFont(font)
        self.label_137.setObjectName("label_137")
        self.gridLayout_13.addWidget(self.label_137, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_63.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_63.setReadOnly(True)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout_13.addWidget(self.lineEdit_63, 3, 1, 1, 1)
        self.label_139 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_139.setObjectName("label_139")
        self.gridLayout_13.addWidget(self.label_139, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_64.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_64.setReadOnly(True)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout_13.addWidget(self.lineEdit_64, 0, 1, 1, 1)
        self.label_141 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_141.setObjectName("label_141")
        self.gridLayout_13.addWidget(self.label_141, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_143 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_143.setObjectName("label_143")
        self.gridLayout_13.addWidget(self.label_143, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_144 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_144.setObjectName("label_144")
        self.gridLayout_13.addWidget(self.label_144, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_146 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.gridLayout_13.addWidget(self.label_146, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_145 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_145.setObjectName("label_145")
        self.gridLayout_13.addWidget(self.label_145, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_66.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_66.setReadOnly(True)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout_13.addWidget(self.lineEdit_66, 4, 1, 1, 1)
        self.label_147 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_147.setFont(font)
        self.label_147.setObjectName("label_147")
        self.gridLayout_13.addWidget(self.label_147, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_67.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_67.setReadOnly(True)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.gridLayout_13.addWidget(self.lineEdit_67, 1, 1, 1, 1)
        self.label_136 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_136.setFont(font)
        self.label_136.setObjectName("label_136")
        self.gridLayout_13.addWidget(self.label_136, 1, 0, 1, 1)
        self.label_138 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_138.setFont(font)
        self.label_138.setObjectName("label_138")
        self.gridLayout_13.addWidget(self.label_138, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton.setGeometry(QtCore.QRect(380, 100, 113, 22))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_2.setGeometry(QtCore.QRect(380, 190, 113, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(0, 40, 181, 241))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_40.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_9.addWidget(self.lineEdit_40, 2, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_87.setObjectName("label_87")
        self.gridLayout_9.addWidget(self.label_87, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_88 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_88.setObjectName("label_88")
        self.gridLayout_9.addWidget(self.label_88, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_89 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_89.setObjectName("label_89")
        self.gridLayout_9.addWidget(self.label_89, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_41.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_9.addWidget(self.lineEdit_41, 3, 1, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_90.setObjectName("label_90")
        self.gridLayout_9.addWidget(self.label_90, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_91 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_91.setObjectName("label_91")
        self.gridLayout_9.addWidget(self.label_91, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_38.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_9.addWidget(self.lineEdit_38, 0, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_92.setObjectName("label_92")
        self.gridLayout_9.addWidget(self.label_92, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_93 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_93.setObjectName("label_93")
        self.gridLayout_9.addWidget(self.label_93, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_94 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_94.setObjectName("label_94")
        self.gridLayout_9.addWidget(self.label_94, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_43.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_9.addWidget(self.lineEdit_43, 5, 1, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_95.setObjectName("label_95")
        self.gridLayout_9.addWidget(self.label_95, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_96 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_96.setObjectName("label_96")
        self.gridLayout_9.addWidget(self.label_96, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_42.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_9.addWidget(self.lineEdit_42, 4, 1, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_97.setObjectName("label_97")
        self.gridLayout_9.addWidget(self.label_97, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_98 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_98.setObjectName("label_98")
        self.gridLayout_9.addWidget(self.label_98, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_39.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_9.addWidget(self.lineEdit_39, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.label_3.setObjectName("label_3")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(200, 40, 181, 241))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_52.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_11.addWidget(self.lineEdit_52, 2, 1, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_112.setObjectName("label_112")
        self.gridLayout_11.addWidget(self.label_112, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_113 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_113.setObjectName("label_113")
        self.gridLayout_11.addWidget(self.label_113, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_114 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_114.setObjectName("label_114")
        self.gridLayout_11.addWidget(self.label_114, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_53.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_11.addWidget(self.lineEdit_53, 3, 1, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_115.setObjectName("label_115")
        self.gridLayout_11.addWidget(self.label_115, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_116 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_116.setObjectName("label_116")
        self.gridLayout_11.addWidget(self.label_116, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_50.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_11.addWidget(self.lineEdit_50, 0, 1, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_117.setObjectName("label_117")
        self.gridLayout_11.addWidget(self.label_117, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_118 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_118.setObjectName("label_118")
        self.gridLayout_11.addWidget(self.label_118, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_119 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_119.setObjectName("label_119")
        self.gridLayout_11.addWidget(self.label_119, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_55.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_11.addWidget(self.lineEdit_55, 5, 1, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_120.setObjectName("label_120")
        self.gridLayout_11.addWidget(self.label_120, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_121 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_121.setObjectName("label_121")
        self.gridLayout_11.addWidget(self.label_121, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_54.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_11.addWidget(self.lineEdit_54, 4, 1, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_122.setObjectName("label_122")
        self.gridLayout_11.addWidget(self.label_122, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_123 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_123.setObjectName("label_123")
        self.gridLayout_11.addWidget(self.label_123, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_51.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_11.addWidget(self.lineEdit_51, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(210, 10, 161, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_19.setGeometry(QtCore.QRect(390, 240, 131, 71))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_20.setGeometry(QtCore.QRect(390, 420, 131, 71))
        self.pushButton_20.setObjectName("pushButton_20")
        self.lineEdit_72 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_72.setGeometry(QtCore.QRect(410, 360, 85, 26))
        self.lineEdit_72.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(390, 330, 121, 21))
        self.label_7.setObjectName("label_7")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_21.setGeometry(QtCore.QRect(390, 80, 131, 81))
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(0, 340, 171, 221))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_128 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_128.setObjectName("label_128")
        self.gridLayout_14.addWidget(self.label_128, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_130 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_130.setObjectName("label_130")
        self.gridLayout_14.addWidget(self.label_130, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_140 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_140.setObjectName("label_140")
        self.gridLayout_14.addWidget(self.label_140, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_142 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_142.setObjectName("label_142")
        self.gridLayout_14.addWidget(self.label_142, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_149 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_149.setObjectName("label_149")
        self.gridLayout_14.addWidget(self.label_149, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_150 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_150.setObjectName("label_150")
        self.gridLayout_14.addWidget(self.label_150, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_151 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_151.setObjectName("label_151")
        self.gridLayout_14.addWidget(self.label_151, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_152 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_152.setObjectName("label_152")
        self.gridLayout_14.addWidget(self.label_152, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_153 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_153.setObjectName("label_153")
        self.gridLayout_14.addWidget(self.label_153, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_154 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_154.setObjectName("label_154")
        self.gridLayout_14.addWidget(self.label_154, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_70.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_70.setReadOnly(True)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.gridLayout_14.addWidget(self.lineEdit_70, 5, 1, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_59.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_59.setReadOnly(True)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_14.addWidget(self.lineEdit_59, 0, 1, 1, 1)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_69.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_69.setReadOnly(True)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.gridLayout_14.addWidget(self.lineEdit_69, 4, 1, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_65.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_65.setReadOnly(True)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout_14.addWidget(self.lineEdit_65, 1, 1, 1, 1)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_68.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_68.setReadOnly(True)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.gridLayout_14.addWidget(self.lineEdit_68, 2, 1, 1, 1)
        self.label_155 = QtWidgets.QLabel(self.tab_6)
        self.label_155.setGeometry(QtCore.QRect(10, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_155.setFont(font)
        self.label_155.setObjectName("label_155")
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(200, 340, 171, 221))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_156 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_156.setFont(font)
        self.label_156.setObjectName("label_156")
        self.gridLayout_15.addWidget(self.label_156, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_157 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_157.setObjectName("label_157")
        self.gridLayout_15.addWidget(self.label_157, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_158 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_158.setObjectName("label_158")
        self.gridLayout_15.addWidget(self.label_158, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_159 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_159.setObjectName("label_159")
        self.gridLayout_15.addWidget(self.label_159, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_160 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_160.setObjectName("label_160")
        self.gridLayout_15.addWidget(self.label_160, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_161 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_161.setFont(font)
        self.label_161.setObjectName("label_161")
        self.gridLayout_15.addWidget(self.label_161, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_162 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_162.setObjectName("label_162")
        self.gridLayout_15.addWidget(self.label_162, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_163 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_163.setFont(font)
        self.label_163.setObjectName("label_163")
        self.gridLayout_15.addWidget(self.label_163, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_164 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_164.setFont(font)
        self.label_164.setObjectName("label_164")
        self.gridLayout_15.addWidget(self.label_164, 1, 0, 1, 1)
        self.label_165 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_165.setFont(font)
        self.label_165.setObjectName("label_165")
        self.gridLayout_15.addWidget(self.label_165, 0, 0, 1, 1)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_71.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_71.setReadOnly(True)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.gridLayout_15.addWidget(self.lineEdit_71, 0, 1, 1, 1)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_74.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_74.setReadOnly(True)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.gridLayout_15.addWidget(self.lineEdit_74, 2, 1, 1, 1)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_75.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_75.setReadOnly(True)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.gridLayout_15.addWidget(self.lineEdit_75, 3, 1, 1, 1)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_73.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_73.setReadOnly(True)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.gridLayout_15.addWidget(self.lineEdit_73, 1, 1, 1, 1)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_76.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_76.setReadOnly(True)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.gridLayout_15.addWidget(self.lineEdit_76, 4, 1, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.tab_6)
        self.label_100.setGeometry(QtCore.QRect(210, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.tabWidget.addTab(self.tab_6, "")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(620, 510, 100, 60))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(620, 300, 100, 60))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 20, 191, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(620, 410, 100, 60))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(620, 190, 100, 60))
        self.pushButton_12.setObjectName("pushButton_12")
        MainWindow_modular_robot.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_modular_robot)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 36))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menuROS = QtWidgets.QMenu(self.menubar)
        self.menuROS.setObjectName("menuROS")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow_modular_robot.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_2.setFont(font)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_3.setFont(font)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_5.setFont(font)
        self.action_5.setObjectName("action_5")
        self.action_8 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_8.setFont(font)
        self.action_8.setObjectName("action_8")
        self.action_4 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_4.setFont(font)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow_modular_robot)
        self.action_6.setCheckable(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_6.setFont(font)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow_modular_robot)
        self.action_7.setCheckable(True)
        self.action_7.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_7.setFont(font)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(MainWindow_modular_robot)
        self.action_9.setCheckable(True)
        self.action_9.setChecked(False)
        self.action_9.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_9.setFont(font)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_10.setFont(font)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_11.setFont(font)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow_modular_robot)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action_12.setFont(font)
        self.action_12.setObjectName("action_12")
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_8)
        self.menu_2.addAction(self.action_11)
        self.menuROS.addAction(self.action_6)
        self.menuROS.addAction(self.action_12)
        self.menu_3.addAction(self.action_10)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuROS.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow_modular_robot)
        self.tabWidget.setCurrentIndex(4)
        self.pushButton_8.clicked.connect(MainWindow_modular_robot.quick_stop)
        self.pushButton_7.clicked['bool'].connect(MainWindow_modular_robot.halt)
        self.pushButton_10.clicked.connect(MainWindow_modular_robot.stop_robot)
        self.pushButton_12.clicked.connect(MainWindow_modular_robot.start_robot)
        self.pushButton_6.clicked.connect(MainWindow_modular_robot.joint_velocity_set_posMode)
        self.pushButton_15.clicked['bool'].connect(MainWindow_modular_robot.joint_i1_vel_command)
        self.radioButton.clicked.connect(MainWindow_modular_robot.set_base_0)
        self.radioButton_2.clicked.connect(MainWindow_modular_robot.set_base_6)
        self.pushButton_9.clicked['bool'].connect(MainWindow_modular_robot.joint_i5_vel_command)
        self.pushButton_17.clicked.connect(MainWindow_modular_robot.joint_velocity_set_velMode)
        self.pushButton_33.clicked.connect(MainWindow_modular_robot.get_inverse_solution)
        self.pushButton_34.clicked.connect(MainWindow_modular_robot.descartes_command)
        self.pushButton_16.clicked['bool'].connect(MainWindow_modular_robot.joint_t4_vel_command)
        self.pushButton_14.clicked['bool'].connect(MainWindow_modular_robot.joint_t3_vel_command)
        self.pushButton_11.clicked.connect(MainWindow_modular_robot.load_point_file)
        self.tabWidget.currentChanged['int'].connect(MainWindow_modular_robot.tab_change)
        self.pushButton_18.clicked.connect(MainWindow_modular_robot.set_path_max_velovity)
        self.pushButton_13.clicked['bool'].connect(MainWindow_modular_robot.joint_t2_vel_command)
        self.pushButton_4.clicked.connect(MainWindow_modular_robot.joint_t4_command)
        self.pushButton_2.clicked.connect(MainWindow_modular_robot.joint_t2_command)
        self.pushButton_24.clicked.connect(MainWindow_modular_robot.operate_point_data)
        self.pushButton.clicked.connect(MainWindow_modular_robot.joint_i1_command)
        self.pushButton_3.clicked.connect(MainWindow_modular_robot.joint_t3_command)
        self.pushButton_5.clicked.connect(MainWindow_modular_robot.joint_i5_command)
        self.pushButton_19.clicked.connect(MainWindow_modular_robot.translate_relative_position_to_base)
        self.pushButton_20.clicked.connect(MainWindow_modular_robot.run_translation_to_base)
        self.pushButton_21.clicked['bool'].connect(MainWindow_modular_robot.receive_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_modular_robot)

    def retranslateUi(self, MainWindow_modular_robot):
        _translate = QtCore.QCoreApplication.translate
        self.lineEdit_9.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-120~120度</p></body></html>"))
        self.label_14.setText(_translate("MainWindow_modular_robot", "关节_T2"))
        self.label_20.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_15.setText(_translate("MainWindow_modular_robot", "关节_T3"))
        self.label_18.setText(_translate("MainWindow_modular_robot", "deg"))
        self.lineEdit_11.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_8.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-120~120度</p></body></html>"))
        self.label_21.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_16.setText(_translate("MainWindow_modular_robot", "关节_T4"))
        self.lineEdit_7.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_19.setText(_translate("MainWindow_modular_robot", "deg"))
        self.pushButton_5.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_2.setText(_translate("MainWindow_modular_robot", "运行"))
        self.label_13.setText(_translate("MainWindow_modular_robot", "关节_I1"))
        self.label_17.setText(_translate("MainWindow_modular_robot", "关节_I5"))
        self.pushButton_3.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_4.setText(_translate("MainWindow_modular_robot", "运行"))
        self.label_22.setText(_translate("MainWindow_modular_robot", "deg"))
        self.lineEdit_10.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-120~120度</p></body></html>"))
        self.label_23.setText(_translate("MainWindow_modular_robot", "关节速度"))
        self.lineEdit_12.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p align=\"center\">1~30度/秒</p></body></html>"))
        self.label_24.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.pushButton_6.setText(_translate("MainWindow_modular_robot", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_modular_robot", "关节空间位置控制"))
        self.label_35.setText(_translate("MainWindow_modular_robot", "关节_T2"))
        self.pushButton_9.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_16.setText(_translate("MainWindow_modular_robot", "运行"))
        self.label_37.setText(_translate("MainWindow_modular_robot", "关节_T3"))
        self.label_42.setText(_translate("MainWindow_modular_robot", "关节_I1"))
        self.label_40.setText(_translate("MainWindow_modular_robot", "关节_T4"))
        self.pushButton_15.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_14.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_13.setText(_translate("MainWindow_modular_robot", "运行"))
        self.label_43.setText(_translate("MainWindow_modular_robot", "关节_I5"))
        self.label_45.setText(_translate("MainWindow_modular_robot", "关节速度"))
        self.lineEdit_23.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p align=\"center\">1~30度/秒</p></body></html>"))
        self.label_46.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.pushButton_17.setText(_translate("MainWindow_modular_robot", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow_modular_robot", "关节空间速度控制"))
        self.pushButton_24.setText(_translate("MainWindow_modular_robot", "运行"))
        self.pushButton_11.setText(_translate("MainWindow_modular_robot", "载入文件"))
        self.pushButton_18.setText(_translate("MainWindow_modular_robot", "速度设置"))
        self.lineEdit.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>速度范围1-30度/s</p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow_modular_robot", "5"))
        self.label_2.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_modular_robot", "离线轨迹点控制"))
        self.lineEdit_28.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_61.setText(_translate("MainWindow_modular_robot", "Y"))
        self.label_62.setText(_translate("MainWindow_modular_robot", "Z"))
        self.label_63.setText(_translate("MainWindow_modular_robot", "X"))
        self.lineEdit_29.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_70.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_66.setText(_translate("MainWindow_modular_robot", "RZ"))
        self.lineEdit_26.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_69.setText(_translate("MainWindow_modular_robot", "mm"))
        self.label_72.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_71.setText(_translate("MainWindow_modular_robot", "deg"))
        self.lineEdit_31.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_68.setText(_translate("MainWindow_modular_robot", "mm"))
        self.label_67.setText(_translate("MainWindow_modular_robot", "mm"))
        self.lineEdit_30.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_64.setText(_translate("MainWindow_modular_robot", "RX"))
        self.label_65.setText(_translate("MainWindow_modular_robot", "RY"))
        self.lineEdit_27.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_32.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_73.setText(_translate("MainWindow_modular_robot", "Y"))
        self.label_74.setText(_translate("MainWindow_modular_robot", "Z"))
        self.label_75.setText(_translate("MainWindow_modular_robot", "X"))
        self.lineEdit_33.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_76.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_77.setText(_translate("MainWindow_modular_robot", "RZ"))
        self.lineEdit_34.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_78.setText(_translate("MainWindow_modular_robot", "mm/s"))
        self.label_79.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_80.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.lineEdit_35.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_81.setText(_translate("MainWindow_modular_robot", "mm/s"))
        self.label_82.setText(_translate("MainWindow_modular_robot", "mm/s"))
        self.lineEdit_36.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_83.setText(_translate("MainWindow_modular_robot", "RX"))
        self.label_84.setText(_translate("MainWindow_modular_robot", "RY"))
        self.lineEdit_37.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_85.setText(_translate("MainWindow_modular_robot", "笛卡尔位置命令"))
        self.label_86.setText(_translate("MainWindow_modular_robot", "笛卡尔速度命令"))
        self.label_99.setText(_translate("MainWindow_modular_robot", "关节速度命令"))
        self.label_126.setText(_translate("MainWindow_modular_robot", "I1"))
        self.lineEdit_57.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_56.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_124.setText(_translate("MainWindow_modular_robot", "T2"))
        self.label_125.setText(_translate("MainWindow_modular_robot", "T3"))
        self.label_127.setText(_translate("MainWindow_modular_robot", "deg"))
        self.lineEdit_58.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_129.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_131.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_132.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_135.setText(_translate("MainWindow_modular_robot", "I5"))
        self.lineEdit_60.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_133.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_134.setText(_translate("MainWindow_modular_robot", "T4"))
        self.lineEdit_61.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_148.setText(_translate("MainWindow_modular_robot", "关节位置命令"))
        self.pushButton_33.setText(_translate("MainWindow_modular_robot", "获取逆解"))
        self.pushButton_34.setText(_translate("MainWindow_modular_robot", "运行"))
        self.lineEdit_62.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_137.setText(_translate("MainWindow_modular_robot", "T3"))
        self.lineEdit_63.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_139.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.lineEdit_64.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_141.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_143.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_144.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_146.setText(_translate("MainWindow_modular_robot", "T4"))
        self.label_145.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.lineEdit_66.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_147.setText(_translate("MainWindow_modular_robot", "I5"))
        self.lineEdit_67.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_136.setText(_translate("MainWindow_modular_robot", "T2"))
        self.label_138.setText(_translate("MainWindow_modular_robot", "I1"))
        self.radioButton.setText(_translate("MainWindow_modular_robot", "G0_基座"))
        self.radioButton_2.setText(_translate("MainWindow_modular_robot", "G6_基座"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow_modular_robot", "笛卡尔空间位置控制"))
        self.lineEdit_40.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_87.setText(_translate("MainWindow_modular_robot", "Y"))
        self.label_88.setText(_translate("MainWindow_modular_robot", "Z"))
        self.label_89.setText(_translate("MainWindow_modular_robot", "X"))
        self.lineEdit_41.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_90.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_91.setText(_translate("MainWindow_modular_robot", "RZ"))
        self.lineEdit_38.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_92.setText(_translate("MainWindow_modular_robot", "mm"))
        self.label_93.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_94.setText(_translate("MainWindow_modular_robot", "deg"))
        self.lineEdit_43.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_95.setText(_translate("MainWindow_modular_robot", "mm"))
        self.label_96.setText(_translate("MainWindow_modular_robot", "mm"))
        self.lineEdit_42.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_97.setText(_translate("MainWindow_modular_robot", "RX"))
        self.label_98.setText(_translate("MainWindow_modular_robot", "RY"))
        self.lineEdit_39.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_3.setText(_translate("MainWindow_modular_robot", "接收笛卡尔位置显示"))
        self.lineEdit_52.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_112.setText(_translate("MainWindow_modular_robot", "Y"))
        self.label_113.setText(_translate("MainWindow_modular_robot", "Z"))
        self.label_114.setText(_translate("MainWindow_modular_robot", "X"))
        self.lineEdit_53.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_115.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_116.setText(_translate("MainWindow_modular_robot", "RZ"))
        self.lineEdit_50.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_117.setText(_translate("MainWindow_modular_robot", "mm"))
        self.label_118.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_119.setText(_translate("MainWindow_modular_robot", "deg"))
        self.lineEdit_55.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_120.setText(_translate("MainWindow_modular_robot", "mm"))
        self.label_121.setText(_translate("MainWindow_modular_robot", "mm"))
        self.lineEdit_54.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_122.setText(_translate("MainWindow_modular_robot", "RX"))
        self.label_123.setText(_translate("MainWindow_modular_robot", "RY"))
        self.lineEdit_51.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_5.setText(_translate("MainWindow_modular_robot", "到基座笛卡尔位置显示"))
        self.pushButton_19.setText(_translate("MainWindow_modular_robot", "位置转换"))
        self.pushButton_20.setText(_translate("MainWindow_modular_robot", "运行"))
        self.lineEdit_72.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_7.setText(_translate("MainWindow_modular_robot", "转换后是否正确"))
        self.pushButton_21.setText(_translate("MainWindow_modular_robot", "Receive  Data"))
        self.label_128.setText(_translate("MainWindow_modular_robot", "I1"))
        self.label_130.setText(_translate("MainWindow_modular_robot", "T2"))
        self.label_140.setText(_translate("MainWindow_modular_robot", "T3"))
        self.label_142.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_149.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_150.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_151.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_152.setText(_translate("MainWindow_modular_robot", "I5"))
        self.label_153.setText(_translate("MainWindow_modular_robot", "deg"))
        self.label_154.setText(_translate("MainWindow_modular_robot", "T4"))
        self.lineEdit_70.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_59.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_69.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_65.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_68.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_155.setText(_translate("MainWindow_modular_robot", "转换后关节位置命令"))
        self.label_156.setText(_translate("MainWindow_modular_robot", "T3"))
        self.label_157.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_158.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_159.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_160.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_161.setText(_translate("MainWindow_modular_robot", "T4"))
        self.label_162.setText(_translate("MainWindow_modular_robot", "deg/s"))
        self.label_163.setText(_translate("MainWindow_modular_robot", "I5"))
        self.label_164.setText(_translate("MainWindow_modular_robot", "T2"))
        self.label_165.setText(_translate("MainWindow_modular_robot", "I1"))
        self.lineEdit_71.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_74.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_75.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_73.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_76.setToolTip(_translate("MainWindow_modular_robot", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_100.setText(_translate("MainWindow_modular_robot", "转换后关节速度命令"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow_modular_robot", "接收数据"))
        self.pushButton_8.setText(_translate("MainWindow_modular_robot", "急停"))
        self.pushButton_7.setText(_translate("MainWindow_modular_robot", "暂停 "))
        self.label.setText(_translate("MainWindow_modular_robot", "机器人未使能"))
        self.pushButton_10.setText(_translate("MainWindow_modular_robot", "停止"))
        self.pushButton_12.setText(_translate("MainWindow_modular_robot", "启动"))
        self.menu.setTitle(_translate("MainWindow_modular_robot", "文件"))
        self.menu_2.setTitle(_translate("MainWindow_modular_robot", "工具"))
        self.menuROS.setTitle(_translate("MainWindow_modular_robot", "ROS"))
        self.menu_3.setTitle(_translate("MainWindow_modular_robot", "帮助"))
        self.action.setText(_translate("MainWindow_modular_robot", "夹持器"))
        self.action_2.setText(_translate("MainWindow_modular_robot", "示教点记录"))
        self.action_3.setText(_translate("MainWindow_modular_robot", "零点设置"))
        self.action_5.setText(_translate("MainWindow_modular_robot", "退出"))
        self.action_8.setText(_translate("MainWindow_modular_robot", "自主抓夹"))
        self.action_4.setText(_translate("MainWindow_modular_robot", "关于"))
        self.action_6.setText(_translate("MainWindow_modular_robot", "状态反馈"))
        self.action_7.setText(_translate("MainWindow_modular_robot", "速度消息"))
        self.action_9.setText(_translate("MainWindow_modular_robot", "电流消息"))
        self.action_10.setText(_translate("MainWindow_modular_robot", "关于"))
        self.action_11.setText(_translate("MainWindow_modular_robot", "机器人状态反馈"))
        self.action_12.setText(_translate("MainWindow_modular_robot", "控制命令"))

