# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gripper_control.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_gripper(object):
    def setupUi(self, Form_gripper):
        Form_gripper.setObjectName("Form_gripper")
        Form_gripper.resize(491, 157)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form_gripper.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(Form_gripper)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 301, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form_gripper)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(320, 60, 160, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form_gripper)
        self.label_7.setGeometry(QtCore.QRect(520, 230, 39, 79))
        self.label_7.setObjectName("label_7")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form_gripper)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 331, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 3, 1, 1)

        self.retranslateUi(Form_gripper)
        self.pushButton.clicked['bool'].connect(Form_gripper.gripper_0_open)
        self.pushButton_3.clicked['bool'].connect(Form_gripper.gripper_0_close)
        self.pushButton_2.clicked['bool'].connect(Form_gripper.gripper_6_open)
        self.pushButton_4.clicked['bool'].connect(Form_gripper.gripper_6_close)
        self.pushButton_5.clicked.connect(Form_gripper.gripper_torque_set)
        QtCore.QMetaObject.connectSlotsByName(Form_gripper)

    def retranslateUi(self, Form_gripper):
        _translate = QtCore.QCoreApplication.translate
        Form_gripper.setWindowTitle(_translate("Form_gripper", "夹持器控制"))
        self.label_2.setText(_translate("Form_gripper", "夹持器_G6  "))
        self.pushButton.setText(_translate("Form_gripper", "开启"))
        self.pushButton_2.setText(_translate("Form_gripper", "开启"))
        self.label.setText(_translate("Form_gripper", "夹持器_G0  "))
        self.pushButton_3.setText(_translate("Form_gripper", "关闭"))
        self.pushButton_4.setText(_translate("Form_gripper", "关闭"))
        self.lineEdit_2.setToolTip(_translate("Form_gripper", "<html><head/><body><p>整数0~2000</p></body></html>"))
        self.lineEdit_3.setToolTip(_translate("Form_gripper", "<html><head/><body><p>整数0~2000</p></body></html>"))
        self.label_8.setText(_translate("Form_gripper", "mA"))
        self.label_9.setText(_translate("Form_gripper", "mA"))
        self.label_7.setText(_translate("Form_gripper", "mA"))
        self.label_4.setText(_translate("Form_gripper", "mA"))
        self.label_3.setText(_translate("Form_gripper", "夹持器力矩  "))
        self.lineEdit.setToolTip(_translate("Form_gripper", "<html><head/><body><p>整数0~2000</p></body></html>"))
        self.pushButton_5.setText(_translate("Form_gripper", "设置"))

