# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_feedback.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_robotFeedback(object):
    def setupUi(self, robotFeedback):
        robotFeedback.setObjectName("robotFeedback")
        robotFeedback.resize(774, 334)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(robotFeedback)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 40, 171, 281))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_42.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_10.addWidget(self.lineEdit_42, 2, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.gridLayout_10.addWidget(self.label_85, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_86 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.gridLayout_10.addWidget(self.label_86, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_87 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.gridLayout_10.addWidget(self.label_87, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_43.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_10.addWidget(self.lineEdit_43, 3, 1, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_96.setFont(font)
        self.label_96.setObjectName("label_96")
        self.gridLayout_10.addWidget(self.label_96, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_97 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        self.gridLayout_10.addWidget(self.label_97, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_44.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_44.setReadOnly(True)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_10.addWidget(self.lineEdit_44, 0, 1, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_98.setFont(font)
        self.label_98.setObjectName("label_98")
        self.gridLayout_10.addWidget(self.label_98, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_99 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.gridLayout_10.addWidget(self.label_99, 5, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_100 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayout_10.addWidget(self.label_100, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_45.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_10.addWidget(self.lineEdit_45, 5, 1, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridLayout_10.addWidget(self.label_101, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_102 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.gridLayout_10.addWidget(self.label_102, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_46.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_46.setReadOnly(True)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_10.addWidget(self.lineEdit_46, 4, 1, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")
        self.gridLayout_10.addWidget(self.label_103, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_104 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_104.setFont(font)
        self.label_104.setObjectName("label_104")
        self.gridLayout_10.addWidget(self.label_104, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_47.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_47.setReadOnly(True)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_10.addWidget(self.lineEdit_47, 1, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(robotFeedback)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(200, 40, 171, 231))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_48.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_48.setReadOnly(True)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_11.addWidget(self.lineEdit_48, 2, 1, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_105.setFont(font)
        self.label_105.setObjectName("label_105")
        self.gridLayout_11.addWidget(self.label_105, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_106 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_106.setFont(font)
        self.label_106.setObjectName("label_106")
        self.gridLayout_11.addWidget(self.label_106, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_107 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.gridLayout_11.addWidget(self.label_107, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_49.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_49.setReadOnly(True)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_11.addWidget(self.lineEdit_49, 3, 1, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        self.gridLayout_11.addWidget(self.label_108, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_50.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_50.setReadOnly(True)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_11.addWidget(self.lineEdit_50, 0, 1, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_109.setFont(font)
        self.label_109.setObjectName("label_109")
        self.gridLayout_11.addWidget(self.label_109, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_110 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_110.setFont(font)
        self.label_110.setObjectName("label_110")
        self.gridLayout_11.addWidget(self.label_110, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_111 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.gridLayout_11.addWidget(self.label_111, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_112 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_112.setFont(font)
        self.label_112.setObjectName("label_112")
        self.gridLayout_11.addWidget(self.label_112, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_113 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_113.setFont(font)
        self.label_113.setObjectName("label_113")
        self.gridLayout_11.addWidget(self.label_113, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_114 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_114.setFont(font)
        self.label_114.setObjectName("label_114")
        self.gridLayout_11.addWidget(self.label_114, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_51.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_51.setReadOnly(True)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_11.addWidget(self.lineEdit_51, 4, 1, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_52.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_52.setReadOnly(True)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_11.addWidget(self.lineEdit_52, 1, 1, 1, 1)
        self.label_115 = QtWidgets.QLabel(robotFeedback)
        self.label_115.setGeometry(QtCore.QRect(590, 10, 141, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_115.setFont(font)
        self.label_115.setObjectName("label_115")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(robotFeedback)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(590, 40, 171, 231))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_53.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_53.setReadOnly(True)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_12.addWidget(self.lineEdit_53, 2, 1, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_116.setFont(font)
        self.label_116.setObjectName("label_116")
        self.gridLayout_12.addWidget(self.label_116, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_117 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_117.setFont(font)
        self.label_117.setObjectName("label_117")
        self.gridLayout_12.addWidget(self.label_117, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_118 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_118.setFont(font)
        self.label_118.setObjectName("label_118")
        self.gridLayout_12.addWidget(self.label_118, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_54.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_54.setReadOnly(True)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_12.addWidget(self.lineEdit_54, 3, 1, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_119.setFont(font)
        self.label_119.setObjectName("label_119")
        self.gridLayout_12.addWidget(self.label_119, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_55.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_55.setReadOnly(True)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_12.addWidget(self.lineEdit_55, 0, 1, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_120.setFont(font)
        self.label_120.setObjectName("label_120")
        self.gridLayout_12.addWidget(self.label_120, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_121 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_121.setFont(font)
        self.label_121.setObjectName("label_121")
        self.gridLayout_12.addWidget(self.label_121, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_122 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_122.setFont(font)
        self.label_122.setObjectName("label_122")
        self.gridLayout_12.addWidget(self.label_122, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_123 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_123.setFont(font)
        self.label_123.setObjectName("label_123")
        self.gridLayout_12.addWidget(self.label_123, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_124 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_124.setFont(font)
        self.label_124.setObjectName("label_124")
        self.gridLayout_12.addWidget(self.label_124, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_125 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_125.setFont(font)
        self.label_125.setObjectName("label_125")
        self.gridLayout_12.addWidget(self.label_125, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_56.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_56.setReadOnly(True)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_12.addWidget(self.lineEdit_56, 4, 1, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_57.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_57.setReadOnly(True)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_12.addWidget(self.lineEdit_57, 1, 1, 1, 1)
        self.label_126 = QtWidgets.QLabel(robotFeedback)
        self.label_126.setGeometry(QtCore.QRect(10, 10, 141, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_126.setFont(font)
        self.label_126.setObjectName("label_126")
        self.label_127 = QtWidgets.QLabel(robotFeedback)
        self.label_127.setGeometry(QtCore.QRect(200, 10, 141, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_127.setFont(font)
        self.label_127.setObjectName("label_127")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(robotFeedback)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(390, 40, 181, 231))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_58.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_58.setReadOnly(True)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_13.addWidget(self.lineEdit_58, 2, 1, 1, 1)
        self.label_128 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_128.setFont(font)
        self.label_128.setObjectName("label_128")
        self.gridLayout_13.addWidget(self.label_128, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_129 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_129.setFont(font)
        self.label_129.setObjectName("label_129")
        self.gridLayout_13.addWidget(self.label_129, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_130 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.gridLayout_13.addWidget(self.label_130, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_59.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_59.setReadOnly(True)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_13.addWidget(self.lineEdit_59, 3, 1, 1, 1)
        self.label_131 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_131.setFont(font)
        self.label_131.setObjectName("label_131")
        self.gridLayout_13.addWidget(self.label_131, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_60.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_60.setReadOnly(True)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout_13.addWidget(self.lineEdit_60, 0, 1, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_132.setFont(font)
        self.label_132.setObjectName("label_132")
        self.gridLayout_13.addWidget(self.label_132, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_133 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_133.setFont(font)
        self.label_133.setObjectName("label_133")
        self.gridLayout_13.addWidget(self.label_133, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_134 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_134.setFont(font)
        self.label_134.setObjectName("label_134")
        self.gridLayout_13.addWidget(self.label_134, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_135 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_135.setFont(font)
        self.label_135.setObjectName("label_135")
        self.gridLayout_13.addWidget(self.label_135, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_136 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_136.setFont(font)
        self.label_136.setObjectName("label_136")
        self.gridLayout_13.addWidget(self.label_136, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_137 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_137.setFont(font)
        self.label_137.setObjectName("label_137")
        self.gridLayout_13.addWidget(self.label_137, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_61.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_61.setReadOnly(True)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout_13.addWidget(self.lineEdit_61, 4, 1, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_62.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_62.setReadOnly(True)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_13.addWidget(self.lineEdit_62, 1, 1, 1, 1)
        self.label_138 = QtWidgets.QLabel(robotFeedback)
        self.label_138.setGeometry(QtCore.QRect(390, 10, 141, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_138.setFont(font)
        self.label_138.setObjectName("label_138")

        self.retranslateUi(robotFeedback)
        QtCore.QMetaObject.connectSlotsByName(robotFeedback)

    def retranslateUi(self, robotFeedback):
        _translate = QtCore.QCoreApplication.translate
        robotFeedback.setWindowTitle(_translate("robotFeedback", "机器人状态反馈"))
        self.lineEdit_42.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_85.setText(_translate("robotFeedback", "Y"))
        self.label_86.setText(_translate("robotFeedback", "Z"))
        self.label_87.setText(_translate("robotFeedback", "X"))
        self.lineEdit_43.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_96.setText(_translate("robotFeedback", "deg"))
        self.label_97.setText(_translate("robotFeedback", "RZ"))
        self.lineEdit_44.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_98.setText(_translate("robotFeedback", "mm"))
        self.label_99.setText(_translate("robotFeedback", "deg"))
        self.label_100.setText(_translate("robotFeedback", "deg"))
        self.lineEdit_45.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_101.setText(_translate("robotFeedback", "mm"))
        self.label_102.setText(_translate("robotFeedback", "mm"))
        self.lineEdit_46.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_103.setText(_translate("robotFeedback", "RX"))
        self.label_104.setText(_translate("robotFeedback", "RY"))
        self.lineEdit_47.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_48.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_105.setText(_translate("robotFeedback", "T2"))
        self.label_106.setText(_translate("robotFeedback", "T3"))
        self.label_107.setText(_translate("robotFeedback", "I1"))
        self.lineEdit_49.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_108.setText(_translate("robotFeedback", "deg"))
        self.lineEdit_50.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_109.setText(_translate("robotFeedback", "deg"))
        self.label_110.setText(_translate("robotFeedback", "deg"))
        self.label_111.setText(_translate("robotFeedback", "deg"))
        self.label_112.setText(_translate("robotFeedback", "deg"))
        self.label_113.setText(_translate("robotFeedback", "T4"))
        self.label_114.setText(_translate("robotFeedback", "I5"))
        self.lineEdit_51.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_52.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_115.setText(_translate("robotFeedback", "关节电流反馈"))
        self.lineEdit_53.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_116.setText(_translate("robotFeedback", "T2"))
        self.label_117.setText(_translate("robotFeedback", "T3"))
        self.label_118.setText(_translate("robotFeedback", "I1"))
        self.lineEdit_54.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_119.setText(_translate("robotFeedback", "mA"))
        self.lineEdit_55.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_120.setText(_translate("robotFeedback", "mA"))
        self.label_121.setText(_translate("robotFeedback", "mA"))
        self.label_122.setText(_translate("robotFeedback", "mA"))
        self.label_123.setText(_translate("robotFeedback", "mA"))
        self.label_124.setText(_translate("robotFeedback", "T4"))
        self.label_125.setText(_translate("robotFeedback", "I5"))
        self.lineEdit_56.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_57.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_126.setText(_translate("robotFeedback", "笛卡尔位置反馈"))
        self.label_127.setText(_translate("robotFeedback", "关节位置反馈"))
        self.lineEdit_58.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_128.setText(_translate("robotFeedback", "T2"))
        self.label_129.setText(_translate("robotFeedback", "T3"))
        self.label_130.setText(_translate("robotFeedback", "I1"))
        self.lineEdit_59.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_131.setText(_translate("robotFeedback", "deg/s"))
        self.lineEdit_60.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_132.setText(_translate("robotFeedback", "deg/s"))
        self.label_133.setText(_translate("robotFeedback", "deg/s"))
        self.label_134.setText(_translate("robotFeedback", "deg/s"))
        self.label_135.setText(_translate("robotFeedback", "deg/s"))
        self.label_136.setText(_translate("robotFeedback", "T4"))
        self.label_137.setText(_translate("robotFeedback", "I5"))
        self.lineEdit_61.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.lineEdit_62.setToolTip(_translate("robotFeedback", "<html><head/><body><p>-360~360度</p></body></html>"))
        self.label_138.setText(_translate("robotFeedback", "关节速度反馈"))

