# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zero_point_set.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_zero_point(object):
    def setupUi(self, Form_zero_point):
        Form_zero_point.setObjectName("Form_zero_point")
        Form_zero_point.resize(413, 291)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form_zero_point.setFont(font)
        self.pushButton = QtWidgets.QPushButton(Form_zero_point)
        self.pushButton.setGeometry(QtCore.QRect(320, 160, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form_zero_point)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 20, 281, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form_zero_point)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 70, 281, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form_zero_point)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 120, 281, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form_zero_point)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 170, 281, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_4.addWidget(self.checkBox_4)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form_zero_point)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 220, 281, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_5.addWidget(self.checkBox_5)
        self.pushButton_2 = QtWidgets.QPushButton(Form_zero_point)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 30, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form_zero_point)
        self.pushButton.clicked.connect(Form_zero_point.set_zero_point)
        self.pushButton_2.clicked.connect(Form_zero_point.get_actual_joint_point)
        QtCore.QMetaObject.connectSlotsByName(Form_zero_point)

    def retranslateUi(self, Form_zero_point):
        _translate = QtCore.QCoreApplication.translate
        Form_zero_point.setWindowTitle(_translate("Form_zero_point", "零点设置"))
        self.pushButton.setText(_translate("Form_zero_point", "设置"))
        self.label.setText(_translate("Form_zero_point", "关节_I1 "))
        self.lineEdit.setToolTip(_translate("Form_zero_point", "<html><head/><body><p>两位小数-360~360度</p></body></html>"))
        self.checkBox.setText(_translate("Form_zero_point", "正向"))
        self.label_2.setText(_translate("Form_zero_point", "关节_T2"))
        self.lineEdit_2.setToolTip(_translate("Form_zero_point", "<html><head/><body><p>两位小数-120~120度</p></body></html>"))
        self.checkBox_2.setText(_translate("Form_zero_point", "正向"))
        self.label_3.setText(_translate("Form_zero_point", "关节_T3"))
        self.lineEdit_3.setToolTip(_translate("Form_zero_point", "<html><head/><body><p>两位小数-120~120度</p></body></html>"))
        self.checkBox_3.setText(_translate("Form_zero_point", "正向"))
        self.label_4.setText(_translate("Form_zero_point", "关节_T4"))
        self.lineEdit_4.setToolTip(_translate("Form_zero_point", "<html><head/><body><p>两位小数-120~120度</p></body></html>"))
        self.checkBox_4.setText(_translate("Form_zero_point", "正向"))
        self.label_5.setText(_translate("Form_zero_point", "关节_I5 "))
        self.lineEdit_5.setToolTip(_translate("Form_zero_point", "<html><head/><body><p>两位小数-360~360度</p></body></html>"))
        self.checkBox_5.setText(_translate("Form_zero_point", "正向"))
        self.pushButton_2.setText(_translate("Form_zero_point", "获取当\n"
"前位置"))

